#!/bin/sh

. /lib/lsb/init-functions

case "${1}" in
   start)
      if [ -c "/dev/hwrng" ] ; then
         log_info_msg "Starting rng daemon..."
         start_daemon /usr/sbin/rngd
         evaluate_retval
      fi
      ;;

   stop)
      log_info_msg "Stopping rng daemon..."
      killproc /usr/sbin/rngd
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc /usr/sbin/rngd
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart|status}"
      exit 1
      ;;
esac

exit 0
