#!/bin/bash

WGETLIST="http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz"
MD5SUMLIST="50f97f4159805e374639a73e2636f22e"

installation() {
  ./configure --prefix=/usr
  make
  make DESTDIR=${FAKEROOT} install
}
